#ifndef CONFIG_H
#define CONFIG_H

//#define WITH_LEDS

#define WITH_DS18B20
//#define WITH_TEMPERATURE

#define WITH_PCF8574
#define WITH_INPUTS

//#define WITH_SPEEDO
//#define WITH_TACHO
//#define WITH_ODOMETER

#define WITH_VOLTAGE
#define VOLTAGE_NOTIFICATION_PERIODICALLY
#define VOLTAGE_NOTIFICATION_ABS

//#define WITH_RTC
//#define WITH_MPL115A2
#define WITH_WIFI_AP

#define WITH_SELFHOLD

#endif // CONFIG_H
